### ISSUE TITLE
Signature error

### ISSUE THREAD

**Issue by luu-alex** [AEON-Project/GameOn-TON-Hackathon#11]
Followed docs, looked at the other closed issue but im still getting signature error
```
require('dotenv').config();
import * as crypto from 'crypto';
const appID = process.env.APP_ID;
const secretKey = process.env.SECRET_KEY;
const merchantID = process.env.MERCHANT_ID;
const testUserID = "testemail@qq.com";
if (!appID || !secretKey || !merchantID) {
    console.log("error")
}
export const createOrder = (orderAmount: number = 1) => {
    const jsonData = {
        "appId": appID,
        "merchantOrderNo": merchantID,
        "orderAmount": orderAmount,
        "payCurrency": "USD",
        "paymentToken": "USDT",
        "paymentExchange": "16f021b0-f220-4bbb-aa3b-82d423301957",
        "userId": testUserID
    }
    
    const payCurrency = 'USD';
    const paymentExchange = "16f021b0-f220-4bbb-aa3b-82d423301957";
    const paymentTokens = "USDT";

    const prepareSigning = "appId=" + appID + "&merchantOrderNo=" + merchantID + "&orderAmount=" + orderAmount + "&payCurrency=" + payCurrency + "&paymentExchange=" + paymentExchange + "&paymentTokens=" + paymentTokens + "&userId=" + testUserID + "&key=" + secretKey;

    
    // perform SHA-512
    const signature = hashWithSHA512(prepareSigning).toUpperCase();
    console.log(signature)


}

function hashWithSHA512(data: string): string {

    return crypto.createHash('sha512').update(data).digest('hex');
};


```

**Comment by Koala-AEON** [comment]
Please use the code below:
const crypto = require('crypto');

function sortObjectKeys(obj, secretKey) {
    const keysToFilter = ['orderModel', 'sign', 'paymentNetworks','payType','expiredTime','customParam','callbackURL','redirectURL',];

    const sortedString = Object.keys(obj)
        .sort()
        .filter(key => obj[key] !== '' && !keysToFilter.includes(key)) 
        .map(key => `${key}=${obj[key]}`) 
        .join('&'); 

    return `${sortedString}&key=${secretKey}`;
}

function hashWithSHA512(aValue ) {
    aValue = aValue.trim();
    let buffer;
    try {
        buffer = Buffer.from(aValue, "UTF-8");
    } catch (error) {
        buffer = Buffer.from(aValue); 
    }
    const hash = crypto.createHash('sha512');
    hash.update(buffer);
    return toHex(hash.digest());
}

function toHex(input) {
    if (!input) return null;
    return input.toString('hex').toUpperCase();
}

function verifySignature(data, secret, signature) {
    const calculatedSignature = hashWithSHA512(data, secret);
    return calculatedSignature === signature.toUpperCase();
}

// json data
const jsonData = ``;
// secret
const secret = "";

const data = JSON.parse(jsonData);
signContent = sortObjectKeys(data,secret)
console.log('signContent:', signContent);

// sign
const signature = hashWithSHA512(signContent);
console.log('Signature:', signature);

**Comment by luu-alex** [comment]
Hi. I've tried this and its still not working

**Comment by hoangtv13** [comment]
I also failed to verify signature from webhook data
Here is my gen signature code
```
import { sha512 } from 'js-sha512';

const keysToFilter = [
  'orderModel',
  'sign',
  'paymentNetworks',
  'payType',
  'expiredTime',
  'customParam',
  'callbackURL',
  'redirectURL',
  'address',
  'payNo',
];

const generateSignature = (obj: object, secretKey: string) => {
  const sortedString = Object.keys(obj)
    .sort()
    .filter((key) => obj[key] !== '' && !keysToFilter.includes(key))
    .map((key) => `${key}=${obj[key]}`)
    .join('&');
  const stringToSign = `${sortedString}&key=${secretKey}`;
  const b = sha512(stringToSign).toUpperCase();

  return b;
};
```

**Comment by luu-alex** [comment]
did it work? whats the api path ur using

**Comment by Koala-AEON** [comment]
Hi, please check:https://aeon-xyz.readme.io/docs/webhook-for-order-status-cp
Not every parameter need to sign, you can check the table in doc.
<img width="825" alt="image" src="https://github.com/user-attachments/assets/4b425565-fe46-4b83-bb81-89b9b1bd6f81">

**Comment by Koala-AEON** [comment]
> did it work? whats the api path ur using

You may try again now

**Comment by luu-alex** [comment]
What is webhook paramter am i supposed to use that? is that correct, im using the telegram bot create order bot https://aeon-xyz.readme.io/docs/create-order-bot-telegram-cp

**Comment by luu-alex** [comment]
@Koala-AEON

**Comment by Koala-AEON** [comment]
> What is webhook paramter am i supposed to use that? is that correct, im using the telegram bot create order bot https://aeon-xyz.readme.io/docs/create-order-bot-telegram-cp

You may send callbackURL through create-order-bot, which the address would receive webhook.
callbackURL (The address receiving order webhook)

**Comment by hoangtv13** [comment]
> Copied! Quote reply
> Referen

I did but 2 signature still not match

**Comment by Koala-AEON** [comment]
> > Copied! Quote reply
> > Referen
> 
> I did but 2 signature still not match

Are you in telegram group? 
You may place the parameter there and my coworkers would check together
