### ISSUE TITLE
Integrate with AEON?

### ISSUE THREAD

**Issue by dao0dev** [AEON-Project/GameOn-TON-Hackathon#2]
Team: https://dorahacks.io/buidl/16599
[I don't know how to get apiKey and ](https://aeon-xyz.readme.io/docs/about-the-sign-cp)

How to get apiKey, appId, sign , merchantOrderNo? I don't undestand 
I must to be use https://aeon-xyz.readme.io/docs/create-order-bot-telegram-cp?
When I get my API key, where should I use it?

These are not my questions https://aeon-xyz.readme.io/discuss/66fa25d739a7b0003b1db61e, but they are common questions that interest everyone. I think it would be good to create a section to address these questions.

**Comment by alohaleonardo** [comment]
Yes, you are required to integrate with one of the AEON payment APIs (e.g., https://aeon-xyz.readme.io/docs/crypto-payment) in your game.

I've updated the instruction of getting APIKey and AppId in the Readme. You need to fill a onboarding form and send it to support@aeon.xyz.

**Comment by hoangtv13** [comment]
@alohaleonardo Hi. I got a question. What is merchantOrderNo and userId params in the request? Does it come from our app where integrate AEON or from your side?
