### ISSUE TITLE
Signature, is not verify

### ISSUE THREAD

**Issue by dao0dev** [AEON-Project/GameOn-TON-Hackathon#3]
```js
const crypto = require('crypto');

function generateSignature(data, secretKey) {
  // Сортируем ключи объекта по алфавиту
  const sortedKeys = Object.keys(data).sort();
  
  // Создаём строку в формате URL-запроса
  const queryString = sortedKeys.map(key => `${key}=${data[key]}`).join('&');
  const stringToSign = `${queryString}&key=${secretKey}`;
  console.log(stringToSign);
  console.log("appId=TEST000001&merchantOrderNo=11126&orderAmount=1000&payCurrency=USD&paymentExchange=16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420&paymentTokens=USDT,ETH&userId=505884978@qq.com&key=ixdFyEZzZo7m95dr7qWAjKBaEj4qSMMdeSmW0b5nCak");
  return crypto.createHash('sha512')
      .update(stringToSign)
      .digest('hex')
      .toUpperCase();
}

const jsData = {
  "appId": "TEST000001",
  "merchantOrderNo": "11126",
  "userId": "505884978@qq.com",
  "orderAmount": "1000",
  "payCurrency": "USD",
  "paymentTokens": "USDT,ETH",
  "paymentExchange": "16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420"
}
console.log(generateSignature(jsData, "ixdFyEZzZo7m95dr7qWAjKBaEj4qSMMdeSmW0b5nCak"));
```
I get the signature 3962E8FF2ABD24B806D744C6630B95A05855A2AB86944CCF52009D6E2582787EB0F34CFF323843DDA55B148D770390598AF335DDBECC61D702AA1A87EE93D1E0
I need to get 3962E8FF2ABD24B806D744C6630B95A05855A2AB86944CCF52009D6E2582787EB0F34CFF323843DDA55B148D770390598AF335DDBECC61D702AA1A87EE93D

```1E0``` I get ...1e0???

**Comment by yuanzd123** [comment]
Same here, maybe their typo...

**Comment by Koala-AEON** [comment]
> ```js
> const crypto = require('crypto');
> 
> function generateSignature(data, secretKey) {
>   // Сортируем ключи объекта по алфавиту
>   const sortedKeys = Object.keys(data).sort();
>   
>   // Создаём строку в формате URL-запроса
>   const queryString = sortedKeys.map(key => `${key}=${data[key]}`).join('&');
>   const stringToSign = `${queryString}&key=${secretKey}`;
>   console.log(stringToSign);
>   console.log("appId=TEST000001&merchantOrderNo=11126&orderAmount=1000&payCurrency=USD&paymentExchange=16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420&paymentTokens=USDT,ETH&userId=505884978@qq.com&key=ixdFyEZzZo7m95dr7qWAjKBaEj4qSMMdeSmW0b5nCak");
>   return crypto.createHash('sha512')
>       .update(stringToSign)
>       .digest('hex')
>       .toUpperCase();
> }
> 
> const jsData = {
>   "appId": "TEST000001",
>   "merchantOrderNo": "11126",
>   "userId": "505884978@qq.com",
>   "orderAmount": "1000",
>   "payCurrency": "USD",
>   "paymentTokens": "USDT,ETH",
>   "paymentExchange": "16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420"
> }
> console.log(generateSignature(jsData, "ixdFyEZzZo7m95dr7qWAjKBaEj4qSMMdeSmW0b5nCak"));
> ```
> 
> I get the signature 3962E8FF2ABD24B806D744C6630B95A05855A2AB86944CCF52009D6E2582787EB0F34CFF323843DDA55B148D770390598AF335DDBECC61D702AA1A87EE93D1E0 I need to get 3962E8FF2ABD24B806D744C6630B95A05855A2AB86944CCF52009D6E2582787EB0F34CFF323843DDA55B148D770390598AF335DDBECC61D702AA1A87EE93D
> 
> `1E0` I get ...1e0???

Hi, we have reply this issue in telegram group.

Please sign using the following demo:

const crypto = require('crypto');

function sortObjectKeys(obj, secretKey) {
    const keysToFilter = ['orderModel', 'sign', 'paymentNetworks','payType','expiredTime','customParam','callbackURL','redirectURL',];

    const sortedString = Object.keys(obj)
        .sort()
        .filter(key => obj[key] !== '' && !keysToFilter.includes(key)) 
        .map(key => `${key}=${obj[key]}`) 
        .join('&'); 

    return `${sortedString}&key=${secretKey}`; 
}

function hashWithSHA512(aValue ) {
    aValue = aValue.trim();

    
    let buffer;
    try {
        buffer = Buffer.from(aValue, "UTF-8");
    } catch (error) {
        buffer = Buffer.from(aValue); 
    }

    
    const hash = crypto.createHash('sha512');
    hash.update(buffer);
    return toHex(hash.digest());
}

function toHex(input) {
    if (!input) return null;
    return input.toString('hex').toUpperCase(); 
}

function verifySignature(data, secret, signature) {
    const calculatedSignature = hashWithSHA512(data, secret);
    return calculatedSignature === signature.toUpperCase();
}


const jsonData = `{"paymentExchange":"","orderAmount":"1600","redirectURL":"","appId":"123456","payCurrency":"EUR","paymentTokens":"","callbackURL":"","merchantOrderNo":"234567543213456","userId":"234232","customParam":"","orderModel":"RECHARGE"}`;

const data = JSON.parse(jsonData);
const secret = "123456";

signContent = sortObjectKeys(data,secret)
console.log('signContent:', signContent);


const signature = hashWithSHA512(signContent);
console.log('Signature:', signature);


// data.sign = "";
// const isVerified = verifySignature(signContent, secret, data.sign);
// console.log('Verification successful:', isVerified);

**Comment by yuanzd123** [comment]
Thanks, it works now.

**Comment by hoangtv13** [comment]
@yuanzd123  Hi. I got a question. What is merchantOrderNo and userId params in the request? Does it come from our app where integrate AEON or from AEON ?

**Comment by yuanzd123** [comment]
You generate them

**Comment by hoangtv13** [comment]
> You generate them

I tried but when request to `open/api/payment/V2` it response signature error. I'm using generate hash snippet which @Koala-AEON provide
