### ISSUE TITLE
AEON order query missing timestamp

### ISSUE THREAD

**Issue by athevinha** [AEON-Project/GameOn-TON-Hackathon#4]
In the AEON order query, the timestamp is missing when orders are created. While I could add it as a custom parameter in my Telegram Mini App, this isn't convenient or secure. If the team has a solution for this, please let me know.

**Comment by alohaleonardo** [comment]
We'll add orderTime and payTime to the query order endpoint. Stay tuned.

**Comment by Koala-AEON** [comment]
Hi! the api is updated, please check the doc below:
https://aeon-xyz.readme.io/docs/query-order-cp

> In the AEON order query, the timestamp is missing when orders are created. While I could add it as a custom parameter in my Telegram Mini App, this isn't convenient or secure. If the team has a solution for this, please let me know.

**Comment by athevinha** [comment]
Thanks for your update
