### ISSUE TITLE
Error code 8016 when using tgPayment

### ISSUE THREAD

**Issue by yuanzd123** [AEON-Project/GameOn-TON-Hackathon#6]
I am able to create order through this endpoint: https://sbx-crypto-payment-api.aeon.xyz/open/api/payment
with this orderData:
  let orderData: OrderData = {
    appId: 'myappId assigned by AEON',
    merchantOrderNo: '17243134568514',
    orderAmount: '101',
    payCurrency: 'USD',
    userId: 'userId',
    customParam:
      '{"botName":"RRPaymentTestBot","orderDetail":"ABDC Test BAG ","chatId":"6831529261"}',
    paymentTokens: 'USDT,ETH',
    paymentExchange:
      '16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420',
    orderModel: 'ORDER',
    tgModel: 'BROWSER',
  }

However, I am not able to create order through this endpoint: https://sbx-crypto-payment-api.aeon.xyz/open/api/tgPayment

I got this error:
{
    "code": "8016",
    "msg": "Payment method not supported ",
    "model": null,
    "traceId": "6711c12d8788a6d0f7ebc72cd4ccbb1a",
    "success": false,
    "error": true
}

Can you help me with this?

Thanks,

**Comment by Koala-AEON** [comment]
Sure!
We are working on it and get back to you later.

**Comment by Koala-AEON** [comment]
> I am able to create order through this endpoint: https://sbx-crypto-payment-api.aeon.xyz/open/api/payment with this orderData: let orderData: OrderData = { appId: 'myappId assigned by AEON', merchantOrderNo: '17243134568514', orderAmount: '101', payCurrency: 'USD', userId: 'userId', customParam: '{"botName":"RRPaymentTestBot","orderDetail":"ABDC Test BAG ","chatId":"6831529261"}', paymentTokens: 'USDT,ETH', paymentExchange: '16f021b0-f220-4bbb-aa3b-82d423301957,9226e5c2-ebc3-4fdd-94f6-ed52cdce1420', orderModel: 'ORDER', tgModel: 'BROWSER', }
> 
> However, I am not able to create order through this endpoint: https://sbx-crypto-payment-api.aeon.xyz/open/api/tgPayment
> 
> I got this error: { "code": "8016", "msg": "Payment method not supported ", "model": null, "traceId": "6711c12d8788a6d0f7ebc72cd4ccbb1a", "success": false, "error": true }
> 
> Can you help me with this?
> 
> Thanks,

Please try again, the problem is fixed.

**Comment by yuanzd123** [comment]
Now I have this error instead:

```
response: {
  "code": "8011",
  "msg": "order not already exists",
  "model": null,
  "traceId": "6717453cc69efe52604f9e7f3dc08315",
  "success": false,
  "error": true
}
```

**Comment by yuanzd123** [comment]
it works, thanks
