### ISSUE TITLE
Verify signature

### ISSUE THREAD

**Issue by hoangtv13** [AEON-Project/GameOn-TON-Hackathon#8]
Hi.
How do I verify the signature in the data, because some field that I use to create signature for the order request is not in, or different with field in webhook params.
And in create order, what orderNo is used for when query order, I need to pass merchantOrderNo 
Also response of `open/api/payment/query` is not match with the docs

**Comment by Koala-AEON** [comment]
Hi.
1.How to sign:https://aeon-xyz.readme.io/docs/about-the-sign-cp
2.Which parameter to sign:https://aeon-xyz.readme.io/docs/create-order-bot-telegram-cp
3.Yes, you need to pass merchantorderno for query order which is the merchantorderno you pass in create order.
4.Please let us know the response where is confuse you.

**Comment by hoangtv13** [comment]
> Hi. 1.How to sign:https://aeon-xyz.readme.io/docs/about-the-sign-cp 2.Which parameter to sign:https://aeon-xyz.readme.io/docs/create-order-bot-telegram-cp 3.Yes, you need to pass merchantorderno for query order which is the merchantorderno you pass in create order. 4.Please let us know the response where is confuse you.

Thanks for your response. 
May be my questions is not clear.

1. How to I  verify the signature of the payment result notification when the data using to create signature is different with data in webhook params
2. What is orderNo is used for? Because when I need to query order, I need to pass merchantOrderNo, not orderNo
3.  Response of open/api/payment/query is not match with the docs. Here is the response when I call api : 
```
{
  "code": "0",
  "msg": "success",
  "model": {
    "orderNo": "300217298468114881545",
    "orderStatus": "TIMEOUT",
    "userId": "1234567890123456789012345678901234567890",
    "merchantOrderNo": "5681225",
    "orderCurrency": "USD",
    "orderAmount": "1",
    "payCryptoRate": null,
    "payFiatRate": null,
    "payCryptoCurrency": null,
    "payCryptoVolume": null,
    "payCryptoNetwork": null,
    "address": "0xff15e1a4f1e5ef2ff8f35d408c3dfcd8a5cce385",
    "hxAddress": null,
    "customParam": null,
    "sign": null,
    "failReason": null,
    "fee": "0.008",
    "settlementAmount": null,
    "settlementCurrency": null,
    "payNo": null,
    "orderTime": "2024-10-25 17:00:11",
    "payTime": null
  },
  "traceId": "671b663372772cd04f1ca382ff2e08cc",
  "success": true,
  "error": false
}
```

**Comment by Koala-AEON** [comment]
1.
<img width="837" alt="image" src="https://github.com/user-attachments/assets/d1a315fd-7c50-4e7b-873f-1cfbbe51735f">

Hi, please check on doc. Not all the parameter need to be sign.
2.orderNo is order number by our side, you can use it to check order on merchant dashboard.
3.The response in doc for reference only. Synchronous return interface have no sign
